import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";

interface SalaryData {
    name: string;
    month: string;
    baseSalary: number;
    allowance: number;
    overtimeBonus: number;
    profitBonus: number;
    advances: number;
    netSalary: number;
    presentDays: number;
}

export function generateSalaryPDF(
    data: SalaryData
) {
    const doc = new jsPDF();

    // TITLE
    doc.setFontSize(22);

    doc.text(
        "Salary Slip",
        14,
        20
    );

    // STAFF INFO
    doc.setFontSize(12);

    doc.text(
        `Employee: ${data.name}`,
        14,
        35
    );

    doc.text(
        `Month: ${data.month}`,
        14,
        43
    );

    doc.text(
        `Present Days: ${data.presentDays}`,
        14,
        51
    );

    // TABLE
    autoTable(doc, {
        startY: 65,

        head: [
            [
                "Description",
                "Amount",
            ],
        ],

        body: [
            [
                "Base Salary",
                `₹${data.baseSalary}`,
            ],

            [
                "Allowance",
                `₹${data.allowance}`,
            ],

            [
                "OT Bonus",
                `₹${data.overtimeBonus}`,
            ],

            [
                "Profit Bonus",
                `₹${data.profitBonus}`,
            ],

            [
                "Advances",
                `-₹${data.advances}`,
            ],

            [
                "Net Salary",
                `₹${data.netSalary}`,
            ],
        ],
    });

    // FOOTER
    doc.setFontSize(11);

    doc.text(
        "Generated by Employee Management System",
        14,
        150
    );

    // DOWNLOAD
    doc.save(
        `${data.name}-${data.month}.pdf`
    );
}